sonar.projectKey=buckethead
sonar.projectName=Buckethead
sonar.sources=src,src-tauri/src
sonar.exclusions=src-tauri/target/**,node_modules/**,dist/**,.scannerwork/**,src/bindings.ts
sonar.rust.clippy.reportPaths=src-tauri/clippy-report.json
sonar.coverage.exclusions=**/*
