mod commands;
mod error;
mod s3_client;

pub use error::AppError;

pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("warn")),
        )
        .init();

    let builder = tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::list_profiles,
            commands::set_profile,
            commands::set_profile_mfa,
            commands::list_buckets,
            commands::list_objects,
            commands::presign_url,
            commands::get_object_text,
            commands::save_object,
            commands::open_object,
            commands::head_object,
        ]);

    // Export TypeScript bindings in debug builds
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit manually.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .manage(s3_client::AppState(tokio::sync::RwLock::new(s3_client::S3State::default())))
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
