// This file is auto-generated by tauri-specta. Do not edit manually.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listProfiles: () => typedError<ProfileInfo[], string>(__TAURI_INVOKE("list_profiles")),
	setProfile: (profile: string) => typedError<BucketInfo[], string>(__TAURI_INVOKE("set_profile", { profile })),
	setProfileMfa: (profile: string, mfaToken: string) => typedError<BucketInfo[], string>(__TAURI_INVOKE("set_profile_mfa", { profile, mfaToken })),
	listBuckets: () => typedError<BucketInfo[], string>(__TAURI_INVOKE("list_buckets")),
	listObjects: (bucket: string, prefix: string, continuationToken: string | null) => typedError<ListObjectsResult, string>(__TAURI_INVOKE("list_objects", { bucket, prefix, continuationToken })),
	presignUrl: (bucket: string, key: string, expiresIn: number | null) => typedError<string, string>(__TAURI_INVOKE("presign_url", { bucket, key, expiresIn })),
	getObjectText: (bucket: string, key: string) => typedError<string, string>(__TAURI_INVOKE("get_object_text", { bucket, key })),
	saveObject: (bucket: string, key: string) => typedError<boolean, string>(__TAURI_INVOKE("save_object", { bucket, key })),
	openObject: (bucket: string, key: string) => typedError<null, string>(__TAURI_INVOKE("open_object", { bucket, key })),
	headObject: (bucket: string, key: string) => typedError<ObjectMeta, string>(__TAURI_INVOKE("head_object", { bucket, key })),
};

/* Types */
export type BucketInfo = {
	name: string,
	created: string | null,
};

export type ListObjectsResult = {
	folders: string[],
	objects: ObjectInfo[],
	next_token: string | null,
	truncated: boolean,
};

export type ObjectInfo = {
	key: string,
	size: number,
	modified: string | null,
	etag: string | null,
	storage_class: string | null,
};

export type ObjectMeta = {
	content_type: string | null,
	content_length: number | null,
	last_modified: string | null,
	etag: string | null,
	storage_class: string | null,
	cache_control: string | null,
	content_encoding: string | null,
	user_meta: ([string, string])[],
};

export type ProfileInfo = {
	name: string,
	account_id: string | null,
	role: string | null,
	sso: boolean,
	mfa: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

